export const PRODUCT_FETCH_SUCCESS = 'ITEMS_FETCH_SUCCESS';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const ADD_INVOICE_SUCCESS = 'ADD_INVOICE_SUCCESS';
export const GET_INVOICES_SUCCESS = 'GET_INVOICES_SUCCESS';
export const DELETE_INVOICE_SUCCESS = 'DELETE_INVOICE_SUCCESS';
export const SEARCH_PRODUCTS_SUCCESS = 'SEARCH_PRODUCTS_SUCCESS';
export const FETCH_REVENUE_SUCCESS = 'FETCH_REVENUE_SUCCESS';
